[package]
name = "minglog-tauri"
version = "0.1.0"
description = "MingLog Tauri Desktop Application"
authors = ["MingLog Team <dasein1997@outlook.com>"]
license = "AGPL-3.0"
repository = "https://github.com/MMR-MINGriyue/MingLog"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

# File system operations
fs_extra = "1.3"
walkdir = "2.4"

# Database
rusqlite = { version = "0.30", features = ["bundled"] }

# Logging
log = "0.4"
env_logger = "0.10"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

[features]
# This feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
